spring.application.name=minibankingsystem

# SQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.url=jdbc:mysql://localhost:3306
spring.datasource.username=root
spring.datasource.password=password03361
spring.sql.init.mode=always
spring.sql.init.schema-locations=file:../database/schema.sql
spring.sql.init.data-locations=file:../database/seed.sql
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
app.seeder.clear-on-shutdown=false
spring.jpa.properties.hibernate.default_schema=MiniBankingSystem
spring.datasource.hikari.connection-init-sql=USE MiniBankingSystem

# Tokens
jwt.secret=Sbb81MXkJ6uzM4PGHRgaMOEfzPrFl9n9+TrolOLhnQWlvdmqR9QF0FVOR4mngxTk4IVpvNN63A9mNSFrary85Q==
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000
jwt.transaction-token.expiration=300000
app.cookie.secure=false

# Server Port
server.port=8080

# Messages
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false