spring.application.name=minibankingsystem

# SQL

# Tokens
jwt.secret=Sbb81MXkJ6uzM4PGHRgaMOEfzPrFl9n9+TrolOLhnQWlvdmqR9QF0FVOR4mngxTk4IVpvNN63A9mNSFrary85Q==
jwt.access-token.expiration=900000
jwt.refresh-token.expiration=604800000
jwt.transaction-token.expiration=300000

# Server Port
server.port=8080